// <auto-generated />
namespace DMV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<< Updated upstream:DMV/Migrations/202107151738278_init.Designer.cs
    public sealed partial class init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init));
        
        string IMigrationMetadata.Id
        {
            get { return "202107151738278_init"; }
=======
    public sealed partial class init2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init2));
        
        string IMigrationMetadata.Id
        {
            get { return "202107151730406_init2"; }
>>>>>>> Stashed changes:DMV/Migrations/202107151730406_init2.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
